default: # Это имя ДОЛЖНО совпадать с тем, что в dbt_project.yml
  outputs:
    dev:
      type: snowflake
      account: YF50159.eu-central-1
      user: VITALI # Например, VITALIF
      password: Bmw_1728_vitali
      role: ACCOUNTADMIN
      warehouse: PC_DBT_WH
      database: PC_DBT_DB
      schema: dbt_vf # Схема, которую вы указали в dbt Cloud
      threads: 4
  target: dev